baseurl = "http://ambushersound.com/"
title = "AMBUSHER"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "AMBUSHER"
  copyright = "&copy;2020 AMBUSHER"
  sidebarAbout = [
    "Generating live, ambient experiences.",
    "Based in Chicago, Louisville, and Berlin."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "booking@ambushersound.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Engage"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/ambushersound/"
  #googleplus    = "full profile url in googleplus"
  email         = "booking@ambushersound.com"
  twitter       = "https://twitter.com/TAmbusher"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  #github        = "full profile url in github"
  youtube       = "https://www.youtube.com/channel/UCGyWolSnqRttSdFd9Thj8sw"
  #whatsapp      = "wa.me service link"
  soundcloud    = "https://soundcloud.com/ambushersound"
  bandcamp      = "https://ambusher.bandcamp.com"
  spotify       = "https://open.spotify.com/artist/0awQztt9158JRJU2kChI8I"
  apple         = "https://geo.music.apple.com/us/artist/ambusher/1476267313?mt=1&app=music"
  amazon         ="https://music.amazon.com/artists/B0012AD2W0"

